# Generated by Django 5.0.7 on 2024-07-19 00:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes_api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
    ]
